### Obtener todas las especies
GET http://localhost:3000/api/especies

### Obtener una especie por id
GET http://localhost:3000/api/especies/2205b8d9-da9e-4166-861c-61281ede3d72

### Crear una nueva especie
POST http://localhost:3000/api/especies
Content-Type: application/json

{
  "nombre": "Conejo",
  "descripcion": "Mamífero pequeño de orejas largas"
}

### Crear especie con campo extra (probar sanitización)
POST http://localhost:3000/api/especies
Content-Type: application/json

{
  "nombre": "Hamster",
  "descripcion": "Roedor pequeño",
  "esPeligroso": true
}

### Modificar una especie existente
PUT http://localhost:3000/api/especies/b9831746-fedf-46d6-8b87-337b38d9f18d
Content-Type: application/json

{
  "nombre": "Perro",
  "descripcion": "Mamífero doméstico, leal y compañero del ser humano"
}

### Modificar parcialmente una especie (solo descripción)
PATCH http://localhost:3000/api/especies/b9831746-fedf-46d6-8b87-337b38d9f18d
Content-Type: application/json

{
  "descripcion": "Mamífero doméstico muy fiel"
}

### Eliminar una especie
DELETE http://localhost:3000/api/especies/PEGA_UN_ID_REAL_ACA